version: "3"

services:
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - .:/code/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5438:5432"
  bowlingblog:
    image: bowlingblog:latest
    command: dramatiq bowlingblog.tasks.tasks
    volumes:
      - .:/code/
    depends_on:
      - redis
      - db
  flask_app:
    container_name: bowlingblog
    image: bowlingblog:latest
    restart: always
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
    command: ./flask-app.sh
    environment:
      - IS_DOCKER=1
    volumes:
      - .:/code/
    depends_on:
      - bowlingblog
volumes:
  postgres_db:
