"""changed some fields, added desc

Revision ID: 61801f9d3129
Revises: d9ecae6edc60
Create Date: 2022-07-01 20:41:33.572099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61801f9d3129'
down_revision = 'd9ecae6edc60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('description', sa.String(length=2000), nullable=True))
    op.drop_column('users', 'has_input_frames')
    op.drop_column('users', 'total_strikes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_strikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('has_input_frames', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('games', 'description')
    # ### end Alembic commands ###
