"""split patch

Revision ID: c1ceaba752c6
Revises: 13965b7a9214
Create Date: 2022-07-28 22:04:46.817582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ceaba752c6'
down_revision = '13965b7a9214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('splits', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'splits')
    # ### end Alembic commands ###
