"""frames are required

Revision ID: d9ecae6edc60
Revises: 3ec1afebda09
Create Date: 2022-06-21 18:50:40.071976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ecae6edc60'
down_revision = '3ec1afebda09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'frames',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'frames',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    # ### end Alembic commands ###
