"""username field on games for easier display

Revision ID: e2fcea6e7682
Revises: f3176e4142eb
Create Date: 2022-07-05 05:50:14.598219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fcea6e7682'
down_revision = 'f3176e4142eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'username')
    # ### end Alembic commands ###
