"""a date field might be nice to have

Revision ID: f3176e4142eb
Revises: 61801f9d3129
Create Date: 2022-07-01 23:14:27.918834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3176e4142eb'
down_revision = '61801f9d3129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('date', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'date')
    # ### end Alembic commands ###
